sudo: required

language: ruby

before_script:
  - source <(curl -sL https://raw.githubusercontent.com/zuazo/kitchen-in-travis/0.3.0/scripts/start_docker.sh)
script:
  - docker info
  - docker -v
  - bundle exec rspec dockerfile_spec.rb
